Controllers/PessoasController.cs
using Ability.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Ability.Web.Controllers
{
    public class PessoasController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PessoasController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Pessoas
        public async Task<IActionResult> Index()
        {
              return _context.Pessoas != null ? 
                          View(await _context.Pessoas.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Pessoas'  is null.");
        }

        // GET: Pessoas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Pessoas == null)
            {
                return NotFound();
            }

            var pessoa = await _context.Pessoas
                .FirstOrDefaultAsync(m => m.PessoaId == id);
            if (pessoa == null)
            {
                return NotFound();
            }

            return View(pessoa);
        }

        // GET: Pessoas/Create
        public IActionResult Create()
        {
            Pessoa pessoa = new Pessoa();
            //return View();
            return PartialView("_CreatePartialView", pessoa);
        }

        // POST: Pessoas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PessoaId,Nome,Email,Idade")] Pessoa pessoa)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pessoa);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(pessoa);
        }

        // GET: Pessoas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Pessoas == null)
            {
                return NotFound();
            }

            var pessoa = await _context.Pessoas.FindAsync(id);
            if (pessoa == null)
            {
                return NotFound();
            }
            return View(pessoa);
        }

        // POST: Pessoas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PessoaId,Nome,Email,Idade")] Pessoa pessoa)
        {
            if (id != pessoa.PessoaId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pessoa);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PessoaExists(pessoa.PessoaId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pessoa);
        }

        // GET: Pessoas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Pessoas == null)
            {
                return NotFound();
            }

            var pessoa = await _context.Pessoas
                .FirstOrDefaultAsync(m => m.PessoaId == id);
            if (pessoa == null)
            {
                return NotFound();
            }

            return View(pessoa);
        }

        // POST: Pessoas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Pessoas == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Pessoas'  is null.");
            }
            var pessoa = await _context.Pessoas.FindAsync(id);
            if (pessoa != null)
            {
                _context.Pessoas.Remove(pessoa);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PessoaExists(int id)
        {
          return (_context.Pessoas?.Any(e => e.PessoaId == id)).GetValueOrDefault();
        }
    }
}

Controllers/ProdutosController.cs
using Ability.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Ability.Web.Controllers
{
    public class ProdutosController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProdutosController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Produtoes
        public async Task<IActionResult> Index()
        {
              return _context.Produtos != null ? 
                          View(await _context.Produtos.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Produtos'  is null.");
        }

        // GET: Produtoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Produtos == null)
            {
                return NotFound();
            }

            var produto = await _context.Produtos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (produto == null)
            {
                return NotFound();
            }

            return View(produto);
        }

        public IActionResult Create()
        {
            return View();
        }

        // POST: Produtoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Descricao")] Produto produto)
        {
            if (ModelState.IsValid)
            {
                _context.Add(produto);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(produto);
        }

        // GET: Produtoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Produtos == null)
            {
                return NotFound();
            }

            var produto = await _context.Produtos.FindAsync(id);
            if (produto == null)
            {
                return NotFound();
            }
            return View(produto);
        }

        // POST: Produtoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Descricao")] Produto produto)
        {
            if (id != produto.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(produto);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProdutoExists(produto.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(produto);
        }

        // GET: Produtoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Produtos == null)
            {
                return NotFound();
            }

            var produto = await _context.Produtos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (produto == null)
            {
                return NotFound();
            }

            return View(produto);
        }

        // POST: Produtoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Produtos == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Produtos'  is null.");
            }
            var produto = await _context.Produtos.FindAsync(id);
            if (produto != null)
            {
                _context.Produtos.Remove(produto);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProdutoExists(int id)
        {
          return (_context.Produtos?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/Shared/_CustomConfirm.cshtml
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>

<script>
    $(document).ready(function () {
        setTimeout(function () {
            var divElement = document.getElementById('confirmarExclusaoElement');

            var errorMessage = divElement.getAttribute('data-message');

            if (errorMessage !== null && errorMessage !== '') {
                $.alert({
                    title: 'Informação',
                    content: errorMessage,
                });
            }

        }, 1000);
    });

    $(document).ready(function () {
        $("#searchButton").click(function (event) {
            event.preventDefault();
            var searchTerm = $("#searchInput").val().toLowerCase();
            $("tbody tr").each(function () {
                var titulo = $(this).find("td:eq(1)").text().toLowerCase();
                if (titulo.includes(searchTerm)) {
                    $(this).show();
                } else {
                    $(this).hide();
                }
            });
            return false;
        });
    });

    function confirmarExclusao(el) {
        var message = $("#confirmarExclusaoElement").data("message");

        $.confirm({
            title: 'Confirmação',
            content: 'Deseja realmente excluir?',
            buttons: {
                cancel: {
                    text: "Não",
                    btnClass: "btn-primary",
                    action: function () {
                        $.alert('Exclusão cancelada.');
                    }
                },
                confirm: {
                    text: "Sim",
                    btnClass: "btn-danger",
                    action: function () {
                        el.form.submit();
                    }
                }
            }
        });
    }

    function mostrarAlerta(mensagem) {
        $.alert({
            title: 'Informação',
            content: mensagem,
        });
    }

    function confirmarCancelamento(el) {
        $.confirm({
            title: 'Confirmação',
            content: 'Deseja realmente cancelar este pedido?',
            buttons: {
                cancel: {
                    text: "Não",
                    btnClass: "btn-primary",
                    action: function () {
                        $.alert('Cancelamento não realizado.');
                    }
                },
                confirm: {
                    text: "Sim",
                    btnClass: "btn-danger",
                    action: function () {
                        el.form.submit();
                    }
                }
            }
        });
    }

    function limitarTitulo() {
        var titulo = document.getElementById("Titulo").value;
        var contador = document.getElementById("contadorTitulo");
        var limite = 30;
        var caracteresRestantes = limite - titulo.length;

        contador.textContent = "Caracteres restantes: " + caracteresRestantes;

        if (caracteresRestantes < 0) {
            contador.style.color = "red";
        } else {
            contador.style.color = "black";
        }

        if (titulo.length > limite) {
            document.getElementById("Titulo").value = titulo.slice(0, limite);
        }
    }


    function limitarTexto() {
        var texto = document.getElementById("Texto").value;
        var contador = document.getElementById("contadorTexto");
        var limite = 100;
        var caracteresRestantes = limite - texto.length;

        contador.textContent = "Caracteres restantes: " + caracteresRestantes;

        if (caracteresRestantes < 0) {
            contador.style.color = "red";
        } else {
            contador.style.color = "black";
        }

        if (texto.length > limite) {
            document.getElementById("Texto").value = texto.slice(0, limite);
        }
    }

    function limparCampos() {
        document.getElementById("Titulo").value = "";
        document.getElementById("Texto").value = "";

        document.getElementById("ProdutosSelecionados").selectedIndex = -1;

        document.getElementById("contadorTitulo").textContent = "Caracteres restantes: 30";

        document.getElementById("contadorTexto").textContent = "Caracteres restantes: 100";
    }

    function limitarDescricao() {
        var titulo = document.getElementById("descricao").value;
        var contadorDescricao = document.getElementById("contadorDescricao");
        var limite = 30;
        var caracteresRestantes = limite - titulo.length;

        contadorDescricao.textContent = "Caracteres restantes: " + caracteresRestantes;

        if (caracteresRestantes < 0) {
            contadorDescricao.style.color = "red";
        } else {
            contadcontadorDescricaoor.style.color = "black";
        }

        if (titulo.length > limite) {
            document.getElementById("descricao").value = titulo.slice(0, limite);
        }
    }

    function validarFormulario() {
        var produtosSelecionados = document.getElementById("ProdutosSelecionados").selectedOptions;
        var tituloInserido = document.getElementById("Titulo").value;
        var textoInserido = document.getElementById("Texto").value;

        if (produtosSelecionados.length == 0) {
            $.alert({
                title: 'Informação',
                content: "Por favor, selecione pelo menos uma tag.",
            });

            return false; 
        }

        if (tituloInserido == '') {
            $.alert({
                title: 'Informação',
                content: "Por favor, informe o titulo.",
            });

            return false;
        }

        if (textoInserido == '') {
            $.alert({
                title: 'Informação',
                content: "Por favor, informe o texto.",
            });

            return false;
        }

        return true; 
    }
</script>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ability.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Ability.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Ability.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pessoas" asp-action="Index">Pessoas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produtos" asp-action="Index">Produtos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pedidos" asp-action="Index">Pedidos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Ability.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>